### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'kddresults/dnn1layer/training_set_dnnanalysis.csv'

### ISSUE THREAD

**Issue by CHETHANCKM** [rahulvigneswaran/Intrusion-Detection-Systems#6]
Please provide the file **training_set_dnnanalysys.csv**

**Comment by rahulvigneswaran** [comment]
@CHETHANCKM  It's a file where all the training related details are logged. 

https://github.com/rahulvigneswaran/Intrusion-Detection-Systems/blob/058cbfd214aa9098ab4d011f258a96904c70d64e/dnn/dnn1.py#L61

The error is thrown as there is no such directory. Either try changing `kddresults/dnn1layer/training_set_dnnanalysis.csv` to just `training_set_dnnanalysis.csv` or create a directory `kddresults/dnn1layer/` and try again.
